### ISSUE TITLE
Custom Iconography For Dashboards

### ISSUE THREAD

**Issue by jshmllr** [michigan-com/dashbeat#50]
Replacing the emoji with custom SVGs

**Top Video**
- TV (included)
- Sad Face (not included)

**Site Engaged Time**
- Clock (time) 

**Geo Point**
- Location Pin

**Comment by jshmllr** [comment]
Feedback on these to help unify what's already there
![everydash_icons_1](https://cloud.githubusercontent.com/assets/4146776/22439240/79ee5934-e6f4-11e6-9c33-3c1bc518aefc.jpg)

**Comment by travelinreid** [comment]
Are tablet and phone distinct enough?

**Comment by migreva** [comment]
putting the current ones here for comparison. looks like to differentiate, the top and bottom of the phone image are a little thicker than the tablet

<img width="688" alt="screen shot 2017-02-01 at 9 00 54 am" src="https://cloud.githubusercontent.com/assets/2940659/22509671/0fccc3be-e85d-11e6-8939-e22fc85ef34d.png">
